"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
type Mode = "complete" | "scratch";
type Component = { category: string; name: string; weight: number; price: number };
type GroupSet = { id: string; maker: string; name: string; weight: number; price: number; parts: Component[] };
type Override = Component & { id: number; baseName: string; baseWeight: number; source?: string };
type Bike = { id: number; brand: string; name: string; year: number; weight: number; price: number; source?: string; accent: string };

const groupsets: GroupSet[] = [
  { id:"105di2", maker:"SHIMANO", name:"105 Di2 R7170", weight:2995, price:1650000, parts:[{category:"레버",name:"ST-R7170 좌·우",weight:423,price:0},{category:"브레이크 캘리퍼",name:"BR-R7170 앞·뒤",weight:282,price:0},{category:"크랭크",name:"FC-R7100",weight:754,price:0},{category:"앞 변속기",name:"FD-R7150",weight:142,price:0},{category:"뒤 변속기",name:"RD-R7150",weight:302,price:0},{category:"카세트",name:"CS-R7101",weight:361,price:0},{category:"체인",name:"CN-M7100",weight:252,price:0},{category:"로터·배터리·배선",name:"기본 구성",weight:479,price:0}]},
  { id:"ultegra", maker:"SHIMANO", name:"Ultegra Di2 R8170", weight:2716, price:2450000, parts:[
    {category:"레버",name:"ST-R8170 좌·우",weight:391,price:620000},{category:"브레이크 캘리퍼",name:"BR-R8170 앞·뒤",weight:282,price:270000},{category:"크랭크",name:"FC-R8100 52-36T",weight:711,price:390000},{category:"앞 변속기",name:"FD-R8150",weight:116,price:240000},{category:"뒤 변속기",name:"RD-R8150",weight:262,price:380000},{category:"카세트",name:"CS-R8101 11-30T",weight:291,price:150000},{category:"체인",name:"CN-M8100",weight:252,price:55000},{category:"로터·배터리·배선",name:"RT-CL800 외",weight:411,price:345000}]},
  { id:"duraace", maker:"SHIMANO", name:"Dura-Ace Di2 R9270", weight:2438, price:4650000, parts:[
    {category:"레버",name:"ST-R9270 좌·우",weight:350,price:910000},{category:"브레이크 캘리퍼",name:"BR-R9270 앞·뒤",weight:229,price:440000},{category:"크랭크",name:"FC-R9200 52-36T",weight:685,price:690000},{category:"앞 변속기",name:"FD-R9250",weight:96,price:390000},{category:"뒤 변속기",name:"RD-R9250",weight:215,price:690000},{category:"카세트",name:"CS-R9200 11-30T",weight:223,price:390000},{category:"체인",name:"CN-M9100",weight:242,price:75000},{category:"로터·배터리·배선",name:"RT-CL900 외",weight:398,price:1065000}]},
  { id:"force", maker:"SRAM", name:"Force AXS D2", weight:2811, price:2850000, parts:[
    {category:"레버",name:"Force AXS HRD 좌·우",weight:468,price:790000},{category:"브레이크 캘리퍼",name:"Force AXS 앞·뒤",weight:300,price:330000},{category:"크랭크",name:"Force D2 48-35T",weight:717,price:510000},{category:"앞 변속기",name:"Force AXS",weight:174,price:260000},{category:"뒤 변속기",name:"Force AXS",weight:303,price:450000},{category:"카세트",name:"XG-1270 10-33T",weight:266,price:190000},{category:"체인",name:"Force 12s",weight:259,price:60000},{category:"로터·배터리·배선",name:"Paceline·배터리",weight:324,price:260000}]},
  { id:"rival", maker:"SRAM", name:"Rival AXS", weight:3205, price:1850000, parts:[{category:"레버",name:"Rival AXS HRD 좌·우",weight:494,price:0},{category:"브레이크 캘리퍼",name:"Rival AXS 앞·뒤",weight:310,price:0},{category:"크랭크",name:"Rival AXS 48-35T",weight:844,price:0},{category:"앞 변속기",name:"Rival AXS",weight:180,price:0},{category:"뒤 변속기",name:"Rival AXS",weight:366,price:0},{category:"카세트",name:"XG-1250",weight:338,price:0},{category:"체인",name:"Rival 12s",weight:266,price:0},{category:"로터·배터리·기타",name:"기본 구성",weight:407,price:0}]},
  { id:"red", maker:"SRAM", name:"RED AXS E1", weight:2269, price:6100000, parts:[{category:"레버",name:"RED AXS E1 좌·우",weight:416,price:0},{category:"브레이크 캘리퍼",name:"RED AXS 앞·뒤",weight:280,price:0},{category:"크랭크",name:"RED AXS E1",weight:690,price:0},{category:"앞 변속기",name:"RED AXS E1",weight:153,price:0},{category:"뒤 변속기",name:"RED AXS E1",weight:262,price:0},{category:"카세트",name:"XG-1290",weight:175,price:0},{category:"체인",name:"RED 12s",weight:236,price:0},{category:"로터·배터리·기타",name:"기본 구성",weight:57,price:0}]},
  { id:"chorus", maker:"CAMPAGNOLO", name:"Chorus 12 Disc", weight:2582, price:2650000, parts:[{category:"레버",name:"Ergopower Chorus",weight:600,price:0},{category:"브레이크 캘리퍼",name:"Chorus Disc",weight:330,price:0},{category:"크랭크",name:"Chorus 12s",weight:728,price:0},{category:"앞 변속기",name:"Chorus 12s",weight:94,price:0},{category:"뒤 변속기",name:"Chorus 12s",weight:240,price:0},{category:"카세트",name:"Chorus 12s",weight:310,price:0},{category:"체인",name:"Chorus 12s",weight:220,price:0},{category:"로터·기타",name:"기본 구성",weight:60,price:0}]},
  { id:"superrecord", maker:"CAMPAGNOLO", name:"Super Record Wireless", weight:2520, price:7200000, parts:[{category:"레버",name:"Super Record Wireless",weight:600,price:0},{category:"브레이크 캘리퍼",name:"Super Record",weight:290,price:0},{category:"크랭크",name:"Super Record",weight:585,price:0},{category:"앞 변속기",name:"Super Record Wireless",weight:160,price:0},{category:"뒤 변속기",name:"Super Record Wireless",weight:295,price:0},{category:"카세트",name:"Super Record",weight:210,price:0},{category:"체인",name:"Super Record",weight:240,price:0},{category:"로터·배터리·기타",name:"기본 구성",weight:140,price:0}]},
];
const bikes: Bike[] = [{id:1,brand:"SPECIALIZED",name:"Tarmac SL8 Expert",year:2025,weight:7200,price:8900000,source:"https://www.specialized.com",accent:"coral"},{id:2,brand:"CANYON",name:"Ultimate CF SL 8",year:2025,weight:7460,price:5590000,source:"https://www.canyon.com",accent:"blue"}];
const scratchBase: Component[] = [{category:"프레임셋",name:"카본 로드 프레임셋",weight:1650,price:3200000},{category:"휠셋",name:"카본 디스크 휠셋",weight:1450,price:1800000},{category:"타이어·튜브",name:"28c 튜블리스 세트",weight:620,price:240000},{category:"콕핏",name:"핸들바·스템",weight:410,price:550000},{category:"안장·싯포스트",name:"카본 구성",weight:470,price:480000},{category:"페달·기타",name:"페달·바테이프·케이지",weight:690,price:390000}];
const won = (n:number) => `${Math.round(n).toLocaleString("ko-KR")}원`;

export default function Home(){
  const [mode,setMode]=useState<Mode|null>(null), [bikeId,setBikeId]=useState(1), [groupId,setGroupId]=useState("ultegra");
  const [bikeList,setBikeList]=useState<Bike[]>(bikes), [groupList,setGroupList]=useState<GroupSet[]>(groupsets), [editBike,setEditBike]=useState<number|null>(null);
  const [overrides,setOverrides]=useState<Override[]>([]), [custom,setCustom]=useState<Component[]>(scratchBase), [modal,setModal]=useState<"part"|"custom"|"bike"|"group"|null>(null), [saved,setSaved]=useState(false);
  const bike=bikeList.find(b=>b.id===bikeId)||bikeList[0], group=groupList.find(g=>g.id===groupId)||groupList[0];
  useEffect(()=>{const raw=localStorage.getItem("velolab-v3");if(raw)try{const d=JSON.parse(raw);setMode(d.mode);setBikeId(d.bikeId);setGroupId(d.groupId);setOverrides(d.overrides||[]);setCustom(d.custom||scratchBase);setBikeList(d.bikeList||bikes);setGroupList(d.groupList||groupsets)}catch{}},[]);
  const changed=useMemo(()=>overrides.reduce((s,p)=>s+p.baseWeight-p.weight,0),[overrides]), changeCost=useMemo(()=>overrides.reduce((s,p)=>s+p.price,0),[overrides]);
  const scratchWeight=custom.reduce((s,p)=>s+p.weight,0)+group.weight, scratchPrice=custom.reduce((s,p)=>s+p.price,0)+group.price;
  const save=()=>{localStorage.setItem("velolab-v3",JSON.stringify({mode,bikeId,groupId,overrides,custom,bikeList,groupList}));setSaved(true);setTimeout(()=>setSaved(false),1500)};
  const chooseGroup=(id:string)=>{setGroupId(id);setOverrides([])};
  const addOverride=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),category=String(d.get("category")),base=group.parts.find(p=>p.category===category)!;const next:Override={id:Date.now(),category,baseName:base.name,baseWeight:base.weight,name:String(d.get("name")),weight:Number(d.get("weight")),price:Number(d.get("price")),source:String(d.get("source"))};setOverrides(v=>[...v.filter(p=>p.category!==category),next]);setModal(null)};
  const addCustom=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);setCustom(v=>[...v,{category:String(d.get("category")),name:String(d.get("name")),weight:Number(d.get("weight")),price:Number(d.get("price"))}]);setModal(null)};
  const addBike=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),id=editBike||Date.now();const next:Bike={id,brand:String(d.get("brand")).toUpperCase(),name:String(d.get("name")),year:Number(d.get("year")),weight:Number(d.get("weight")),price:Number(d.get("price")),source:String(d.get("source")),accent:"green"};setBikeList(v=>editBike?v.map(b=>b.id===id?next:b):[...v,next]);setBikeId(id);setEditBike(null);setModal(null)};
  const addGroup=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),weight=Number(d.get("weight")),id=`custom-${Date.now()}`;const cats=["레버","브레이크 캘리퍼","크랭크","앞 변속기","뒤 변속기","카세트","체인","로터·배터리·기타"];const parts=cats.map((category,i)=>({category,name:`${String(d.get("name"))} ${category}`,weight:i===7?weight-Math.floor(weight/8)*7:Math.floor(weight/8),price:0}));setGroupList(v=>[...v,{id,maker:String(d.get("maker")).toUpperCase(),name:String(d.get("name")),weight,price:Number(d.get("price")),parts}]);setGroupId(id);setOverrides([]);setModal(null)};
  const currentPart=(cat:string)=>overrides.find(o=>o.category===cat);
  return <main>
    <header><button className="brand brand-button" onClick={()=>setMode(null)}>VELO<span>LAB</span><small>BIKE BUILDER</small></button>{mode&&<nav><a href="#setup">시작 설정</a><a href="#groupset">그룹셋</a><a href="#result">최종 결과</a></nav>}<button className="save" onClick={save}>{saved?"✓ 저장됨":"빌드 저장"}</button></header>
    {!mode ? <section className="start-screen"><div className="start-copy"><p className="eyebrow">CHOOSE YOUR STARTING POINT</p><h1>어디서부터<br/><em>시작할까요?</em></h1><p>완성차의 부품을 교체할지, 빈 프레임부터 한 대를 조립할지 선택하세요. 선택에 따라 필요한 계산만 보여드립니다.</p></div><div className="path-grid"><button className="path-card" onClick={()=>setMode("complete")}><span className="path-no">01</span><div className="path-icon">◯━◯</div><p>COMPLETE BIKE</p><h2>완차에서 바꾸기</h2><small>제조사 완차 무게·가격을 기준으로 그룹셋이나 개별 부품을 교체합니다.</small><b>완차 선택하기 →</b></button><button className="path-card lime" onClick={()=>setMode("scratch")}><span className="path-no">02</span><div className="path-icon">＋</div><p>BUILD FROM SCRATCH</p><h2>처음부터 조립하기</h2><small>프레임, 그룹셋, 휠셋 등 모든 부품을 더해 한 대의 자전거를 완성합니다.</small><b>새 빌드 시작 →</b></button></div></section> : <>
      <section className="flow-hero"><div><button className="back" onClick={()=>setMode(null)}>← 시작 방식 다시 선택</button><p className="eyebrow">{mode==="complete"?"COMPLETE BIKE UPGRADE":"BUILD FROM SCRATCH"}</p><h1>{mode==="complete"?"완차를 더 가볍게.":"부품부터 나만의 한 대로."}</h1><p>{mode==="complete"?"제조사 완차를 기준점으로 삼고 교체되는 무게와 비용만 정확히 계산합니다.":"그룹셋은 한 번에, 나머지 부품은 원하는 구성으로 더해 최종 결과를 확인합니다."}</p></div><div className="live-total"><small>현재 예상 무게</small><strong>{((mode==="complete"?bike.weight-changed:scratchWeight)/1000).toFixed(3)} kg</strong><span>{mode==="complete"?`${changed}g 감량`:won(scratchPrice)}</span></div></section>
      <section className="wrap setup" id="setup"><div className="section-head"><div><p className="eyebrow">01 / STARTING BASE</p><h2>{mode==="complete"?"내 완차를 선택하세요":"프레임과 기본 부품"}</h2>{mode==="complete"&&<p className="sub">예시는 시작점일 뿐입니다. 어떤 제조사·모델이든 직접 추가하고 수정할 수 있습니다.</p>}</div>{mode==="complete"&&<button className="outline" onClick={()=>{setEditBike(null);setModal("bike")}}>＋ 완차 직접 추가</button>}</div>{mode==="complete"?<div className="bike-grid compact">{bikeList.map(b=><div key={b.id} className={`bike-card ${b.accent} ${bikeId===b.id?"selected":""}`} onClick={()=>setBikeId(b.id)}><div className="bike-top"><span>{b.brand}</span><i>{bikeId===b.id?"기준 완차":"선택"}</i></div><div className="bike-art">◯━◯</div><h3>{b.name}</h3><p>{b.year} · 로드 바이크</p><div className="metrics"><div><small>완차 무게</small><strong>{(b.weight/1000).toFixed(2)} kg</strong></div><div><small>구매 가격</small><strong>{(b.price/10000).toLocaleString()}만원</strong></div></div><div className="card-actions">{b.source&&<a href={b.source} target="_blank" onClick={e=>e.stopPropagation()}>근거 링크 ↗</a>}<button onClick={e=>{e.stopPropagation();setEditBike(b.id);setModal("bike")}}>수정</button><button onClick={e=>{e.stopPropagation();if(bikeList.length>1){setBikeList(v=>v.filter(x=>x.id!==b.id));if(bikeId===b.id)setBikeId(bikeList.find(x=>x.id!==b.id)!.id)}}}>삭제</button></div></div>)}</div>:<div className="base-list">{custom.map((p,i)=><div key={i}><span>{p.category}</span><b>{p.name}</b><em>{p.weight}g</em><strong>{won(p.price)}</strong><button onClick={()=>setCustom(v=>v.filter((_,x)=>x!==i))}>×</button></div>)}<button className="add-line" onClick={()=>setModal("custom")}>＋ 기본 부품 추가</button></div>}</section>
      <section className="groupset-section" id="groupset"><div className="wrap"><div className="section-head"><div><p className="eyebrow">02 / GROUPSET</p><h2>대표 로드 그룹셋</h2><p className="sub">시마노 105·울테그라·듀라에이스, SRAM Rival·Force·RED, Campagnolo Chorus·Super Record를 제공합니다.</p></div><button className="outline" onClick={()=>setModal("group")}>＋ 그룹셋 직접 입력</button></div><div className="group-grid">{groupList.map(g=><button key={g.id} className={`group-card ${groupId===g.id?"selected":""}`} onClick={()=>chooseGroup(g.id)}><div><span>{g.maker}</span>{groupId===g.id&&<i>✓ 적용 중</i>}</div><h3>{g.name}</h3><strong>{(g.weight/1000).toFixed(3)} kg</strong><p>그룹셋 총 무게</p><b>{won(g.price)}</b><small>{g.parts.length}개 부품 자동 선택 →</small></button>)}</div><div className="included"><div className="included-title"><div><b>{group.maker} {group.name}</b><span>포함 부품 · 개별 교체 가능</span></div><button className="outline" onClick={()=>setModal("part")}>＋ 한 부품만 변경</button></div>{group.parts.map(p=>{const o=currentPart(p.category);return <div className={`included-row ${o?"changed":""}`} key={p.category}><span>{p.category}</span><div><b>{o?o.name:p.name}</b>{o&&<small>{p.name}에서 변경됨</small>}</div><strong>{o?o.weight:p.weight}g</strong><em>{o?`${o.baseWeight-o.weight>0?"−":"+"}${Math.abs(o.baseWeight-o.weight)}g`:"기본 구성"}</em>{o&&<button onClick={()=>setOverrides(v=>v.filter(x=>x.id!==o.id))}>되돌리기</button>}</div>})}</div></div></section>
      <section className="result-section" id="result"><div className="wrap"><p className="eyebrow">03 / BUILD RESULT</p><h2>최종 빌드 결과</h2>{mode==="complete"?<div className="result-equation"><div><small>기준 완차</small><strong>{(bike.weight/1000).toFixed(2)} kg</strong><span>{won(bike.price)}</span></div><i>＋</i><div><small>개별 변경</small><strong className="gain">− {changed}g</strong><span>+ {won(changeCost)}</span></div><i>＝</i><div className="final"><small>최종 예상</small><strong>{((bike.weight-changed)/1000).toFixed(3)} kg</strong><span>{won(bike.price+changeCost)}</span></div></div>:<div className="result-equation"><div><small>기본 부품 {custom.length}개</small><strong>{(custom.reduce((s,p)=>s+p.weight,0)/1000).toFixed(3)} kg</strong><span>{won(custom.reduce((s,p)=>s+p.price,0))}</span></div><i>＋</i><div><small>{group.name}</small><strong>{(group.weight/1000).toFixed(3)} kg</strong><span>{won(group.price)}</span></div><i>＝</i><div className="final"><small>최종 예상</small><strong>{(scratchWeight/1000).toFixed(3)} kg</strong><span>{won(scratchPrice)}</span></div></div>}<p className="notice">※ 그룹셋 무게와 가격은 예시 기준입니다. 실제 구매 조건과 구성에 맞게 개별 부품을 변경해 주세요.</p></div></section>
    </>}
    {modal&&<div className="modal-back" onMouseDown={()=>setModal(null)}><form className="modal" onSubmit={modal==="part"?addOverride:modal==="custom"?addCustom:modal==="bike"?addBike:addGroup} onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setModal(null)}>×</button>
      {modal==="bike"?(()=>{const b=bikeList.find(x=>x.id===editBike);return <><p className="eyebrow">COMPLETE BIKE</p><h2>{b?"완차 정보 수정":"내 완차 직접 추가"}</h2><label>제조사<input name="brand" required defaultValue={b?.brand}/></label><label>모델명<input name="name" required defaultValue={b?.name}/></label><div className="two"><label>연식<input name="year" type="number" required defaultValue={b?.year||2026}/></label><label>완차 무게 (g)<input name="weight" type="number" required defaultValue={b?.weight}/></label></div><label>내 구매 가격 (원)<input name="price" type="number" required defaultValue={b?.price}/></label><label>제품·무게 근거 링크<input name="source" type="url" defaultValue={b?.source}/></label></>})():modal==="group"?<><p className="eyebrow">CUSTOM GROUPSET</p><h2>그룹셋 직접 입력</h2><label>제조사<input name="maker" required placeholder="예: MICROSHIFT"/></label><label>그룹셋 이름<input name="name" required placeholder="예: Sword 2x10"/></label><div className="two"><label>전체 무게 (g)<input name="weight" type="number" required/></label><label>내 구매 가격 (원)<input name="price" type="number" required/></label></div><p className="form-note">전체 무게를 등록한 뒤 포함 부품 목록에서 각 부품을 실제 값으로 바꿀 수 있습니다.</p></>:modal==="part"?<><p className="eyebrow">PART OVERRIDE</p><h2>그룹셋 부품 하나만 변경</h2><label>변경할 부품<select name="category" required>{group.parts.map(p=><option key={p.category}>{p.category}</option>)}</select></label><label>새 부품명<input name="name" required placeholder="예: Dura-Ace FC-R9200"/></label><div className="two"><label>새 부품 무게 (g)<input name="weight" type="number" required/></label><label>추가 지출 (원)<input name="price" type="number" required defaultValue="0"/></label></div><label>무게 근거 링크<input name="source" type="url" placeholder="https://..."/></label></>:<><p className="eyebrow">ADD COMPONENT</p><h2>기본 부품 추가</h2><label>부품군<input name="category" required placeholder="예: 휠셋"/></label><label>제품명<input name="name" required/></label><div className="two"><label>무게 (g)<input name="weight" type="number" required/></label><label>가격 (원)<input name="price" type="number" required/></label></div></>}<button className="submit">저장하고 계산하기 →</button></form></div>}
    <footer><b>VELO<span>LAB</span></b><p>Build lighter. Ride further.</p><span>입력한 가격과 구성은 현재 기기에 저장됩니다.</span></footer>
  </main>
}
